name: "Build One by One (anyone)"
on:
  workflow_dispatch:
    inputs:

      armbian_target:
        type: choice
        description: 'Build'
        required: false
        options:
        - kernel
        - build
        default: build
        
      armbian_release:
        type: choice
        description: 'Userspace'
        options:
        - jammy
        - mantic
        - bookworm
        - trixie
        - sid
        default: 'jammy'

      armbian_version:
        description: 'Version'
        required: false
        default: ''
jobs:

  build:
    name: "Build Armbian"
    runs-on: ubuntu-latest
    steps:

      - uses: armbian/build@v24.8.1
        with:
          armbian_token:              "${{secrets.GITHUB_TOKEN}}"
          armbian_target:             "${{inputs.armbian_target}}"
          armbian_release:            "${{inputs.armbian_release}}"
          armbian_kernel_branch:      "vendor"
          armbian_ui:                 "server"
          armbian_board:              "radxa-e25"
          armbian_release_tittle:     "Armbian SDK"
          armbian_release_body:       "Virtual images for x86 and arm64"
          armbian_pgp_key:            "${{secrets.GPG_KEY1}}"
          armbian_pgp_password:       "${{secrets.GPG_PASSPHRASE1}}"
